CREATE TABLE `dc_business_america_public_eng` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`aid` INT(10) NULL DEFAULT NULL,
	`mpid` INT(5) NULL DEFAULT NULL COMMENT '公众号id',
	`ctime` INT(18) NULL DEFAULT NULL COMMENT '创建时间',
	`utime` INT(18) NULL DEFAULT NULL COMMENT '更新日期',
	`publisher` INT(2) NULL DEFAULT '0' COMMENT '操作员  bid',
	`branch` VARCHAR(15) NULL DEFAULT '0' COMMENT '操作员部门',
	`see_id` VARCHAR(20) NULL DEFAULT '0' COMMENT '审核人信息 bid',
	`username` VARCHAR(20) NULL DEFAULT NULL COMMENT '姓名',
	`passport_number` VARCHAR(20) NULL DEFAULT NULL COMMENT '护照号码',
	`america_purpose` VARCHAR(50) NULL DEFAULT NULL COMMENT '赴美出行目的',
	`travel_plans_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否有具体的旅行计划   Y有  N没有',
	`arrive_time` VARCHAR(10) NULL DEFAULT NULL COMMENT '抵达时间',
	`stay_time` VARCHAR(10) NULL DEFAULT NULL COMMENT '停留时间',
	`stay_times` VARCHAR(10) NULL DEFAULT NULL COMMENT '停留时间  单位',
	`stay_address` VARCHAR(150) NULL DEFAULT NULL COMMENT '在美停留期间地址',
	`stay_address_two` VARCHAR(150) NULL DEFAULT NULL COMMENT '在美停留期间地址2',
	`stay_city` VARCHAR(50) NULL DEFAULT NULL COMMENT '首晚住宿的城市',
	`stay_province` VARCHAR(50) NULL DEFAULT NULL COMMENT '首晚住宿  州/省',
	`stay_zip` VARCHAR(20) NULL DEFAULT NULL COMMENT '首晚住宿   邮编',
	`travel_cost_pay` VARCHAR(30) NULL DEFAULT NULL COMMENT '支付此次出行费用的个人或组织',
	`contact_name` VARCHAR(15) NULL DEFAULT NULL COMMENT '在美联系人    姓(拼音)',
	`contact_names` VARCHAR(15) NULL DEFAULT NULL COMMENT '在美联系人    名(拼音)',
	`contact_group_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '在美联系人    组织名',
	`contact_relation` VARCHAR(30) NULL DEFAULT NULL COMMENT '在美联系人   关系',
	`contact_address` VARCHAR(150) NULL DEFAULT NULL COMMENT '在美联系人     地址',
	`contact_address_two` VARCHAR(150) NULL DEFAULT NULL COMMENT '在美联系人     地址2',
	`contact_city` VARCHAR(15) NULL DEFAULT NULL COMMENT '在美联系人    城市',
	`contact_province` VARCHAR(15) NULL DEFAULT NULL COMMENT '在美联系人   州/省',
	`contact_zip` VARCHAR(15) NULL DEFAULT NULL COMMENT '在美联系人    邮编',
	`contact_phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '在美联系人     电话',
	`contact_email` VARCHAR(30) NULL DEFAULT NULL COMMENT '在美联系人     邮箱',
	`pay_personal_name` VARCHAR(15) NULL DEFAULT NULL COMMENT '支付费用的个人    姓(拼音)',
	`pay_personal_names` VARCHAR(15) NULL DEFAULT NULL COMMENT '支付费用的个人    名(拼音)',
	`pay_personal_phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '支付费用的个人     电话',
	`pay_personal_email` VARCHAR(30) NULL DEFAULT NULL COMMENT '支付费用的个人     邮箱',
	`pay_personal_relation` VARCHAR(30) NULL DEFAULT NULL COMMENT '支付费用的个人   关系',
	`pay_personal_address_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '支付费用的个人    聚会地址是否相同',
	`pay_personal_address` VARCHAR(150) NULL DEFAULT NULL COMMENT '支付费用的个人     地址',
	`pay_personal_address_two` VARCHAR(150) NULL DEFAULT NULL COMMENT '支付费用的个人     地址2',
	`pay_personal_city` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付费用的个人    城市',
	`pay_personal_province` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付费用的个人     州/省 ',
	`pay_personal_zip` VARCHAR(20) NULL DEFAULT NULL COMMENT '支付费用的个人    邮编',
	`pay_personal_country` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付费用的个人    国家',
	`pay_group_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付费用的组织   名称',
	`pay_group_phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '支付费用的组织   电话',
	`pay_group_relation` VARCHAR(30) NULL DEFAULT NULL COMMENT '支付费用的组织   关系',
	`pay_group_address` VARCHAR(150) NULL DEFAULT NULL COMMENT '支付费用的组织   地址',
	`pay_group_address_two` VARCHAR(150) NULL DEFAULT NULL COMMENT '支付费用的组织   地址2',
	`pay_group_city` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付费用的组织   城市',
	`pay_group_province` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付费用的组织   州/省',
	`pay_group_zip` VARCHAR(20) NULL DEFAULT NULL COMMENT '支付费用的组织   邮编',
	`pay_group_country` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付费用的组织   国家',
	`old_stay_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否在美国停留过',
	`old_visa_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否获得过美国签证',
	`old_visa_time` VARCHAR(10) NULL DEFAULT NULL COMMENT '最近一次获得签证的时间',
	`old_visa_number` VARCHAR(20) NULL DEFAULT NULL COMMENT '最近一次赴美的签证号码',
	`old_visa_type_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否是同一类型的签证',
	`old_visa_country_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否在申请签证的国家或地区申请签证',
	`old_visa_fingerprint_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '你是否采过十指指纹',
	`old_visa_lost_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '您的美国签证是否曾经遗失或被盗',
	`old_visa_lost_time` VARCHAR(10) NULL DEFAULT NULL COMMENT '丢失年份',
	`old_visa_lost_info` VARCHAR(150) NULL DEFAULT NULL COMMENT '丢失解释说明',
	`old_visa_undo_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '签证是否被撤销过',
	`old_visa_undo_info` VARCHAR(150) NULL DEFAULT NULL COMMENT '撤销原因',
	`old_visa_refused_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '您是否曾被美国拒签过',
	`old_visa_refused_info` VARCHAR(150) NULL DEFAULT NULL COMMENT '被美国拒签原因',
	`old_visa_emigrate_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否申请办理过移民',
	`old_visa_emigrate_info` VARCHAR(150) NULL DEFAULT NULL COMMENT '移民原因',
	`associate_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否有同行人',
	`associate_tuxedo_is` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否参团出行',
	`associate_tuxedo_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '同行人信息    团队名称',
	`associate_name_relation` TEXT NULL COMMENT '同行人姓(拼音) 、同行人名(拼音) 、 关系(最多四人)',
	`remark` TEXT NULL COMMENT '备注',
	`status` INT(2) NULL DEFAULT NULL COMMENT '1 新增  2提交审核  3撤回  4审核成功   5python程序出错   6错误信息',
	`pay_money` INT(5) NULL DEFAULT NULL COMMENT '支付金额',
	`aacode` VARCHAR(20) NULL DEFAULT NULL COMMENT '美签系统申请AA码',
	`ques` TEXT NULL COMMENT '错误信息提示',
	`plans_info` TEXT NULL COMMENT '是否有具体的旅行计划>是（到达日期、到达航班、抵达城市、离开日期、离开航班、离美城市）',
	`plans_access` TEXT NULL COMMENT '是否有具体的旅行计划>是 （访问城市）',
	`old_stay_info` TEXT NULL COMMENT '是否在美国停留过>是 （arrived抵达：arrived_time时间、time停留、times单位；license_is:是否有驾照；license:license_num驾照号码、license_state所属洲）',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id` (`id`) USING BTREE,
	INDEX `mpid` (`mpid`) USING BTREE,
	INDEX `ctime` (`ctime`) USING BTREE,
	INDEX `username` (`username`) USING BTREE,
	INDEX `passport_number` (`passport_number`) USING BTREE,
	INDEX `aid` (`aid`) USING BTREE
)
COMMENT='美签英文 public 表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
